### ISSUE TITLE
[path/pathPrefix] add better support for path and pathPrefix

### ISSUE THREAD

**Issue by giogonzo** [buildo/metarpheus#38]
## requirements

not sure what's the problem here, but I'd like to write 

``` scala
pathPrefix("icq") {
  pathPrefix("alerts") {
    // ...
  }
}
```

better, like

``` scala
path("icq" / "alerts")
```

(they are probably not exactly the same, but you get the point ;) )

Currently this is not supported I think:

```
Exception in thread "main" scala.NotImplementedError: an implementation is missing
    at scala.Predef$.$qmark$qmark$qmark(Predef.scala:230)
    at morpheus.extractors.route.package$$anonfun$morpheus$extractors$route$package$$recurse$1$1.apply(route.scala:114)
    at morpheus.extractors.route.package$$anonfun$morpheus$extractors$route$package$$recurse$1$1.apply(route.scala:98)
    at scala.collection.immutable.List.flatMap(List.scala:327)
    at morpheus.extractors.route.package$.morpheus$extractors$route$package$$recurse$1(route.scala:98)
    at morpheus.extractors.route.package$$anonfun$extractRouteTerms$1$$anonfun$apply$2.apply(route.scala:118)
    at morpheus.extractors.route.package$$anonfun$extractRouteTerms$1$$anonfun$apply$2.apply(route.scala:118)
    at scala.Function2$$anonfun$tupled$1.apply(Function2.scala:48)
    at scala.Function2$$anonfun$tupled$1.apply(Function2.scala:47)
    at morpheus.extractors.route.package$$anonfun$extractRouteTerms$1.apply(route.scala:118)
    at morpheus.extractors.route.package$$anonfun$extractRouteTerms$1.apply(route.scala:118)
    at scala.collection.immutable.List.flatMap(List.scala:327)
    at morpheus.extractors.route.package$.extractRouteTerms(route.scala:118)
    at morpheus.extractors.route.package$.extractAllRoutes(route.scala:311)
    at morpheus.extractors.package$$anonfun$3.apply(extractors.scala:20)
    at morpheus.extractors.package$$anonfun$3.apply(extractors.scala:20)
    at scala.collection.immutable.List.flatMap(List.scala:327)
    at morpheus.extractors.package$.extractFullAPI(extractors.scala:20)
    at morpheus.main$.main(main.scala:45)
    at morpheus.main.main(main.scala)
```
## specs

{optional: describe technical specs to implement this feature, if not obvious}
## misc

{optional: other useful info}

**Comment by gabro** [comment]
wiro should mitigate this greatly
